# Generated by Django 2.2.2 on 2020-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_sensor', models.CharField(blank=True, choices=[('1', 'Temperature'), ('2', 'Rain')], max_length=50, null=True)),
            ],
        ),
    ]
