# Generated by Django 2.2.2 on 2020-09-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atria_sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='type_of_sensor',
            field=models.CharField(blank=True, choices=[('1', 'Temperature'), ('2', 'Rain')], max_length=50, null=True, unique=True),
        ),
    ]
