# Generated by Django 2.2.2 on 2020-09-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atria_sensor', '0002_auto_20200905_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='type_of_sensor',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
